cache:
  directories:
    - node_modules

language:
  - php
  - node_js

os: linux
version: ~> 1.0

node_js:
  - "10"

before_install:
  - npm install

jobs:
  include:
    - stage: "Release"
      name: Release build
      if: branch = develop
      script:
        - node ./deploy/update-version.js
        - npm run build
      after_script:
        - git config --global user.email "travis@travis-ci.org"
        - git config --global user.name "Travis CI"
        - git add --all
      deploy:
        provider: pages
        skip_cleanup: false
        github_token: $GITHUB_OAUTH_TOKEN
        target_branch: master
        on:
          branch: develop

  fast_finish: true
